name: CI
on:
  push:
    branches:
        - master
  pull_request:
  workflow_dispatch:
jobs:
  Linux:
    strategy:
        matrix:
          runs-on: ['ubuntu-24.04-arm', 'ubuntu-24.04']
          image: ['debian:bookworm', 'alpine:3.21']
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build container
        run: |
          docker build -t ci .
      - name: Build and test on container
        run: |
          docker run --rm -i ci
  macOS:
    strategy:
      matrix:
        runs-on: ['macos-13', 'macos-14']
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and test
        run: |
          mkdir "build"
          cd "build"
          cmake ..
          make -j"$(sysctl -n hw.ncpu)" shim
          make check
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
  Windows:
    strategy:
      matrix:
        architecture: ['x64', 'x86']
        include:
          - runs-on: windows-2019
            generator: Visual Studio 16 2019
          - runs-on: windows-2022
            generator: Visual Studio 17 2022
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Visual Studio Developer Command Prompt
        uses: microsoft/setup-msbuild@v2
      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake .. -G "${{ matrix.generator }}" -A "${{ matrix.architecture }}"
          cmake --build . --config Release --target shim
          cmake --build . --config Release --target test_runners
          cd "tests"
          ctest -C Release --output-on-failure
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
